[project]
name = "sync"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.7,<3.8"
dependencies = [
    "tensorflow==1.15",
    "agents>=1.4.0",
]
